### ISSUE TITLE
OMDB API Integration not working

### ISSUE THREAD

**Issue by MadhurDixit13** [MadhurDixit13/MovieRecommender#12]
Tried to integrate OMDB API which allows us to integrate with movie databases such as imdb, rotten tomatoes etc but its not working. To be resolved.

**Comment by ATHARVA47** [comment]
Looking into this issue, will update soon.

**Comment by ATHARVA47** [comment]
Resolved the issue with latest branch and also added feature of poster fetching for predicted movies
